### PR TITLE
Add type annotations for `Commentable`

### PR DESCRIPTION
**Pull request by oliverklee**
Also copy these type annotations to the implementing classes.

### CODE REVIEW

**Comment by sabberworm** [comment]
Is it really necessary to repeat type annotations in overrides? Isn’t there some tag (like `@inheritDoc` in Java) that can be used instead?

**Comment by oliverklee** [comment]
Technically, we need to have _something_ - be it either a copy of the iterface's method, or be it `@inheritdoc` (which should be recognized by tools like PHPStan, Psalm and PhpStorm's static analysis).

However, for the human reader who scrolls through the source code, I very strongly prefer copying the type annotations. This is because the human reader would need to click on the `@inheritdoc` annotation (or hover, depending on which plugins are installed) to see the types, which makes quick reading quite impossible.

**Comment by sabberworm** [comment]
> However, for the human reader who scrolls through the source code, I very strongly prefer copying the type annotations. This is because the human reader would need to click on the `@inheritdoc` annotation (or hover, depending on which plugins are installed) to see the types, which makes quick reading quite impossible.

On the other hand, maintenance is going to be a pain when we want to change the signature (unless we have a tool that enforces consistent type annotations).

**Comment by oliverklee** [comment]
> On the other hand, maintenance is going to be a pain when we want to change the signature (unless we have a tool that enforces consistent type annotations).

This indeed is true. PHPStan (on higher levels) will at least warn us if the type annotations get inconsistent.

**Pull request merged**
