### PR TITLE
Drop the quickdump tool

### PR DESCRIPTION
**Pull request by oliverklee**
This tool does not seem to be referenced or documented anywhere.

### CODE REVIEW

**Comment by sabberworm** [comment]
It’s the tool I used to generate the examples in the readme… I think that could be automated though.

**Comment by oliverklee** [comment]
@sabberworm So should we keep the tool (and maybe move it to `bin/`), or should it go?

**Comment by sabberworm** [comment]
I think it should be refactored into a small script that can be called from a github action to automatically update the README.

**Comment by oliverklee** [comment]
I have now created #247 for moving the file out of the `tests/` directory. (I propose we do the refactoring in a separate step.)

**Pull request closed without merging**
