### PR TITLE
Update PHPUnit to 10.2

### PR DESCRIPTION
**Pull request by bartbutler**
Running the test suite was giving me trouble by requiring PHPUnit 5.7, which is quite old. This MR makes the minimal changes necessary to update to 10.2 without modifying the test content in any substantive way.

### CODE REVIEW

**Comment by sabberworm** [comment]
I think we decided on sticking with 5.7 because it supported all the PHP versions we wanted to test on.

**Comment by bartbutler** [comment]
Of course, that's your prerogative, just noting that I had trouble with it on PHP 8.2 for some reason. and arguably nobody should be using PHP 5 at this point given the vast improvement from 5 to 7.

**Comment by sabberworm** [comment]
I definitely think we can finally tackle #251.

**Comment by bartbutler** [comment]
Looks like PHP 5 might finally be below 5% for WP. Anyway, when you decide to do it, this MR is here.

**Comment by oliverklee** [comment]
Hey @bartbutler, I'd like to close this in favor of the (merged) #424. As we're keeping support for PHP 7.2 at the moment, we cannot go higher than PHPUnit 8.

I'd still like to have static data providers. Would you be willing to create a new PR for that?

**Comment by bartbutler** [comment]
Took a look and seems to have already been done, so nothing to do!

**Pull request closed without merging**
